<?php
return ['project-id-version'=>'','report-msgid-bugs-to'=>'','pot-creation-date'=>'2025-03-09 22:35+0000','po-revision-date'=>'2025-03-16 21:18+0000','last-translator'=>'','language-team'=>'Russian','language'=>'ru_RU','plural-forms'=>'nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10 >= 2 && n%10<=4 &&(n%100<10||n%100 >= 20)? 1 : 2);','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','x-generator'=>'Loco https://localise.biz/','x-loco-version'=>'2.7.1; wp-6.7.2','messages'=>['Account created'=>'Аккаунт создан','Avatar'=>'Аватар','Away'=>'Прочь','Busy'=>'Занят','Cache Duration (seconds)'=>'Длительность кэша (секунды)','Copy'=>'Копировать','Could not find Steam profile. Please check your input and try again.'=>'Не удалось найти профиль Steam. Пожалуйста, проверьте введенные вами данные и попробуйте снова.','Done'=>'Выполнено','Duration to cache API results in seconds. Default is 3600 (1 hour).'=>'Длительность кэширования результатов API в секундах. По умолчанию - 3600 (1 час).','Enter SteamID / SteamCommunityID / Profile Name / Profile URL'=>'Введите SteamID / SteamCommunityID / Имя профиля / URL профиля','Enter your Steam API key. You can get one from'=>'Введите свой API-ключ Steam. Вы можете получить его на','Error fetching player data.'=>'Ошибка при извлечении данных плеера.','Error while requesting Steam API:'=>'Ошибка при запросе Steam API:','Find'=>'Найти','Find and get your Steam ID, Steam ID 64, customURL and community ID'=>'Найдите и получите свой Steam ID, Steam ID 64, customURL и community ID','For example:
Heavenanvil
76561198036370701
STEAM_0:1:38052486
steamcommunity.com/id/heavenanvil
steamcommunity.com/profiles/76561198036370701'=>'For example:
Heavenanvil
76561198036370701
STEAM_0:1:38052486
steamcommunity.com/id/heavenanvil
steamcommunity.com/profiles/76561198036370701','Hidden'=>'Скрытый','Level'=>'Уровень','Location'=>'Расположение','Looking to play'=>'Ищу игру','Looking to trade'=>'Ищу торговлю','Player data not found.'=>'Данные игрока не найдены.','Player profile not found.'=>'Профиль игрока не найден.','Private'=>'Частный','Profile URL'=>'URL-адрес профиля','Public'=>'Публичный','Real Name'=>'Настоящее Имя','Snooze'=>'Повтор','Status'=>'Статус','Steam API'=>'Steam API','Steam API Key'=>'Ключ API Steam','Steam API key is not configured.'=>'Ключ Steam API не настроен.','Steam API key is not configured. %sConfigure it now%s.'=>'Ключ API Steam не настроен. %sConfigure это сейчас%s.','Steam API Plugin requires a Steam API key to function. Please %sconfigure it now%s.'=>'Плагин Steam API требует ключа Steam API для функционирования. Пожалуйста, %s настройте это сейчас %s.','Steam API Settings'=>'Настройки Steam API','Steam Web API Key Registration'=>'Регистрация Ключа Steam Web API','SteamID2'=>'SteamID2','SteamID3'=>'SteamID3','SteamID64'=>'SteamID64','The Steam API key appears to be invalid. Please check it and try again.'=>'Ключ API Steam, похоже, недействителен. Пожалуйста, проверьте это и попробуйте снова.','This feature is currently unavailable. Please contact the site administrator.'=>'Эта функция в настоящее время недоступна. Пожалуйста, свяжитесь с администратором сайта.','Unknown'=>'Неизвестный','Unknown error when contacting Steam API'=>'Неизвестная ошибка при обращении к Steam API','Visibility'=>'Видимость','🔴 Offline'=>'🔴 Offline','🟢 Online'=>'🟢 Online']];
