<?php
return ['project-id-version'=>'Steam API Plugin 1.3','pot-creation-date'=>'2025-03-10 12:00+0000','po-revision-date'=>'2025-03-16 21:16+0000','last-translator'=>'','language-team'=>'English (United States)','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','x-generator'=>'Loco https://localise.biz/','x-poedit-keywordslist'=>'__;_e;esc_html__;esc_html_e;esc_attr__;esc_attr_e;_x;_ex;esc_attr_x;esc_html_x;_n;_nx','x-poedit-basepath'=>'..','x-poedit-searchpath-0'=>'.','x-poedit-searchpathexcluded-0'=>'languages','x-poedit-searchpathexcluded-1'=>'.git','report-msgid-bugs-to'=>'','language'=>'en_US','plural-forms'=>'nplurals=2; plural=n != 1;','x-loco-version'=>'2.7.1; wp-6.7.2','messages'=>['Account created'=>'Account created','Avatar'=>'Avatar','Away'=>'Away','Busy'=>'Busy','Cache Duration (seconds)'=>'Cache Duration (seconds)','Copy'=>'Copy','Could not find Steam profile. Please check your input and try again.'=>'Could not find Steam profile. Please check your input and try again.','Done'=>'Done','Duration to cache API results in seconds. Default is 3600 (1 hour).'=>'Duration to cache API results in seconds. Default is 3600 (1 hour).','Enter SteamID / SteamCommunityID / Profile Name / Profile URL'=>'Enter SteamID / SteamCommunityID / Profile Name / Profile URL','Enter your Steam API key. You can get one from'=>'Enter your Steam API key. You can get one from','Error fetching player data.'=>'Error fetching player data.','Error while requesting Steam API:'=>'Error while requesting Steam API:','Find'=>'Find','Find and get your Steam ID, Steam ID 64, customURL and community ID'=>'Find and get your Steam ID, Steam ID 64, customURL and community ID','For example:
Heavenanvil
76561198036370701
STEAM_0:1:38052486
steamcommunity.com/id/heavenanvil
steamcommunity.com/profiles/76561198036370701'=>'For example:
Heavenanvil
76561198036370701
STEAM_0:1:38052486
steamcommunity.com/id/heavenanvil
steamcommunity.com/profiles/76561198036370701','Hidden'=>'Hidden','Level'=>'Level','Location'=>'Location','Looking to play'=>'Looking to play','Looking to trade'=>'Looking to trade','Player data not found.'=>'Player data not found.','Player profile not found.'=>'Player profile not found.','Private'=>'Private','Profile URL'=>'Profile URL','Public'=>'Public','Real Name'=>'Real Name','Snooze'=>'Snooze','Status'=>'Status','Steam API'=>'Steam API','Steam API Key'=>'Steam API Key','Steam API key is not configured.'=>'Steam API key is not configured.','Steam API key is not configured. %sConfigure it now%s.'=>'Steam API key is not configured. %sConfigure it now%s','Steam API Plugin requires a Steam API key to function. Please %sconfigure it now%s.'=>'Steam API Plugin requires a Steam API key to function. Please %sconfigure it now%s.','Steam API Settings'=>'Steam API Settings','Steam Web API Key Registration'=>'Steam Web API Key Registration','SteamID2'=>'SteamID2','SteamID3'=>'SteamID3','SteamID64'=>'SteamID64','The Steam API key appears to be invalid. Please check it and try again.'=>'The Steam API key appears to be invalid. Please check it and try again.','This feature is currently unavailable. Please contact the site administrator.'=>'This feature is currently unavailable. Please contact the site administrator.','Unknown'=>'Unknown','Unknown error when contacting Steam API'=>'Unknown error when contacting Steam API','Visibility'=>'Visibility','🔴 Offline'=>'🔴 Offline','🟢 Online'=>'🟢 Online']];
